// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ninx.Data.Context;

#nullable disable

namespace ninx.Data.Migrations
{
    [DbContext(typeof(NinxDB))]
    partial class NinxDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ninx.Domain.Entities.AssinaturaEletronica", b =>
                {
                    b.Property<int>("AssinaturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssinaturaID"));

                    b.Property<bool>("Assinado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<string>("DispositivoInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DocumentoGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagemAssinatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAssinante")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Ativa");

                    b.Property<int>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("AssinaturaID");

                    b.HasIndex("VendaID");

                    b.ToTable("AssinaturasEletronicas", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssinaturasEletronicas_Status", "[Status] IN ('Ativa', 'Vencida', 'Cancelada')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.AssinaturaPlano", b =>
                {
                    b.Property<int>("AssinaturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssinaturaID"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComercioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Ativa");

                    b.HasKey("AssinaturaID");

                    b.HasIndex("ComercioID");

                    b.ToTable("Assinaturas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assinaturas_Plano", "[Plano] IN ('Mensal', 'Trimestral', 'Anual')");

                            t.HasCheckConstraint("CK_Assinaturas_Status", "[Status] IN ('Ativa', 'Vencida', 'Cancelada')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaID");

                    b.ToTable("CategoriasProduto", (string)null);
                });

            modelBuilder.Entity("ninx.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComercioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteID");

                    b.HasIndex("ComercioID");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ninx.Domain.Entities.Comercio", b =>
                {
                    b.Property<int>("ComercioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComercioID"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeComercio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ComercioID");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasFilter("[CNPJ] IS NOT NULL");

                    b.ToTable("Comercios", (string)null);
                });

            modelBuilder.Entity("ninx.Domain.Entities.Estoque", b =>
                {
                    b.Property<int>("EstoqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstoqueID"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComercioID")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,3)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("QuantidadeMinima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,3)")
                        .HasDefaultValue(0m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("EstoqueID");

                    b.HasIndex("ComercioID");

                    b.HasIndex("ProdutoID")
                        .IsUnique();

                    b.HasIndex("ProdutoID", "ComercioID")
                        .IsUnique();

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("ninx.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<int>("ItemVendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemVendaID"));

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProdutoCodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("ItemVendaID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("VendaID");

                    b.ToTable("ItensVenda", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItensVenda_UnidadeMedida", "[UnidadeMedida] IN ('UN', 'KG', 'L', 'G')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("MovimentacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimentacaoID"));

                    b.Property<int>("ComercioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int?>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("MovimentacaoID");

                    b.HasIndex("ComercioID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("VendaID");

                    b.ToTable("MovimentacoesEstoque", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovimentacoesEstoque_Tipo", "[Tipo] IN ('Entrada', 'Venda', 'Ajuste', 'Perda', 'Devolucao', 'Estorno')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.PagamentoHistoricoAssinaturaPlano", b =>
                {
                    b.Property<int>("PagamentoAssinaturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagamentoAssinaturaID"));

                    b.Property<int>("AssinaturaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PagamentoAssinaturaID");

                    b.HasIndex("AssinaturaID");

                    b.ToTable("PagamentosAssinaturasPlano", (string)null);
                });

            modelBuilder.Entity("ninx.Domain.Entities.PagamentoVenda", b =>
                {
                    b.Property<int>("PagamentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagamentoID"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PagamentoVinculoID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Pago");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("PagamentoID");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("VendaID");

                    b.ToTable("PagamentosVenda", null, t =>
                        {
                            t.HasCheckConstraint("CK_PagamentosVenda_FormaPagamento", "[FormaPagamento] IN ('Dinheiro', 'Pix', 'Cartao')");

                            t.HasCheckConstraint("CK_PagamentosVenda_Status", "[Status] IN ('Pago', 'Estornado')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoID"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ComercioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PrecoCusto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("UN");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("date");

                    b.HasKey("ProdutoID");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("ComercioID", "CodigoBarras")
                        .IsUnique()
                        .HasFilter("[CodigoBarras] IS NOT NULL");

                    b.ToTable("Produtos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Produtos_UnidadeMedida", "[UnidadeMedida] IN ('UN', 'KG', 'L', 'G')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.SessaoWhatsapp", b =>
                {
                    b.Property<int>("SessaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessaoID"));

                    b.Property<int>("ComercioID")
                        .HasColumnType("int");

                    b.Property<string>("DadosTemporarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Menu");

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UltimaInteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SessaoID");

                    b.HasIndex("ComercioID", "NumeroCelular")
                        .IsUnique();

                    b.ToTable("SessoesWhatsapp", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessoesWhatsapp_Etapa", "[Etapa] IN ('Menu', 'AguardandoProduto', 'AguardandoSelecao')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Permissao", "[Permissao] IN ('Administrador', 'Dono', 'Funcionario')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.UsuarioComercio", b =>
                {
                    b.Property<int>("UsuarioComercioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioComercioID"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ComercioID")
                        .HasColumnType("int");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("UsuarioComercioID");

                    b.HasIndex("ComercioID");

                    b.HasIndex("UsuarioID", "ComercioID")
                        .IsUnique();

                    b.ToTable("UsuariosComercios", null, t =>
                        {
                            t.HasCheckConstraint("CK_UsuariosComercios_Permissao", "[Permissao] IN ('Administrador', 'Dono', 'Funcionario')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("VendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaID"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("ComercioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Aberta");

                    b.Property<string>("TipoVenda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("VendaID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("ComercioID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Vendas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vendas_Status", "[Status] IN ('Aberta', 'Finalizada', 'Cancelada', 'Estornada')");

                            t.HasCheckConstraint("CK_Vendas_TipoVenda", "[TipoVenda] IN ('Normal', 'Fiado')");
                        });
                });

            modelBuilder.Entity("ninx.Domain.Entities.AssinaturaEletronica", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Venda", "Venda")
                        .WithMany("AssinaturasEletronicas")
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ninx.Domain.Entities.AssinaturaPlano", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Assinaturas")
                        .HasForeignKey("ComercioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("ninx.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Clientes")
                        .HasForeignKey("ComercioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("ninx.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninx.Domain.Entities.Produto", "Produto")
                        .WithOne("Estoque")
                        .HasForeignKey("ninx.Domain.Entities.Estoque", "ProdutoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comercio");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ninx.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninx.Domain.Entities.Venda", "Venda")
                        .WithMany("ItensVenda")
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ninx.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninx.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninx.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninx.Domain.Entities.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ninx.Domain.Entities.PagamentoHistoricoAssinaturaPlano", b =>
                {
                    b.HasOne("ninx.Domain.Entities.AssinaturaPlano", "Assinatura")
                        .WithMany()
                        .HasForeignKey("AssinaturaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assinatura");
                });

            modelBuilder.Entity("ninx.Domain.Entities.PagamentoVenda", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninx.Domain.Entities.Venda", "Venda")
                        .WithMany("PagamentosVenda")
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ninx.Domain.Entities.Produto", b =>
                {
                    b.HasOne("ninx.Domain.Entities.CategoriaProduto", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaID");

                    b.HasOne("ninx.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Produtos")
                        .HasForeignKey("ComercioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("ninx.Domain.Entities.SessaoWhatsapp", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("ninx.Domain.Entities.UsuarioComercio", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Comercio", "Comercio")
                        .WithMany("UsuarioComercios")
                        .HasForeignKey("ComercioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninx.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioComercios")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ninx.Domain.Entities.Venda", b =>
                {
                    b.HasOne("ninx.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninx.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Vendas")
                        .HasForeignKey("ComercioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninx.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Vendas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Comercio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ninx.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ninx.Domain.Entities.Comercio", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("Clientes");

                    b.Navigation("Produtos");

                    b.Navigation("UsuarioComercios");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ninx.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Estoque");
                });

            modelBuilder.Entity("ninx.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioComercios");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ninx.Domain.Entities.Venda", b =>
                {
                    b.Navigation("AssinaturasEletronicas");

                    b.Navigation("ItensVenda");

                    b.Navigation("PagamentosVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
